/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_haosdent_cgroup_util_Threads */

#ifndef _Included_me_haosdent_cgroup_util_Threads
#define _Included_me_haosdent_cgroup_util_Threads
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_haosdent_cgroup_util_Threads
 * Method:    getThreadId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_haosdent_cgroup_util_Threads_getThreadId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
